### ISSUE TITLE
Program tries to read from 'encoder.json' and 'vocab.bpe' but doesn't supply defaults

### ISSUE THREAD

**Issue by IsaGoodFriend** [Draco18s/NovelAPI#1]
I'm trying to get this code up and running, but as the title states, I don't have either file needed, and I don't know what the format/contents are like to build my own.  I don't even know where to look online to get any examples.

**Comment by Draco18s** [comment]
Oh, uh. I'll get those uploaded for you in a hot minute. The folder I put them in wasn't for git-commit.

Edit: Those are pushed up now. Thanks for letting me know.
