### ISSUE TITLE
Stories seems to be mixing Newtonsoft.JSON and System.Text.JSON methods

### ISSUE THREAD

**Issue by JasonLWalker** [Draco18s/NovelAPI#9]
Newtonsoft.JSON and System.Text.JSON methods are not usually interchangeable.

**Comment by Draco18s** [comment]
Yeah I should standardize, but for the most part I think I ended up using System for incoming packet data, as I didn't necessarily know what the reconstructed object will (or might) look like, but used Newtonsoft anytime I did know what things looked like, as it is more type-strict than System is.

One of those "ok this one isn't doing what I need, use that one" things.

**Comment by JasonLWalker** [comment]
It seems to be causing issues with the GetStories method. I think I just
got it fixed though, and have stories deserialized now. You mentioned that
stories are one thing you're focused on. I'm needing that too, so I was
looking into helping you deserialize the stories and story content if you
want.

**Comment by Draco18s** [comment]
Stories are a "thing I had working before, but I was rewriting the whole solution, and current usage doesn't need them at present" but are at the top of the [NAI related] TODO list. Just several steps below "active development."

For reference, I've been implementing the ideas [in this paper](https://arxiv.org/pdf/2304.03442.pdf) into a discord bot. And yes, I've gotten different characters to interact with each other (it's all the same *bot* just that different context is fed to the LLM and I can use embeds to make the messages come from ghost users, so it looks like multiple bots, but there's only the one). It's pretty neat.

**Comment by JasonLWalker** [comment]
Multiple characters interacting with each other is actually one thing I'm
working on too. 😁

**Comment by Draco18s** [comment]
Nice.

My discord bot code is not in a state where I'm comfortable publishing it, but it has been mentioned before.

**Comment by JasonLWalker** [comment]
Mine is actually for an experimental Visual Novel project.

**Comment by Draco18s** [comment]
Very cool.

If you hadn't seen it: https://www.youtube.com/watch?v=g39AagVW0s0
